### ISSUE TITLE
[Bug]: Application stuck at P3 Pick 14

### ISSUE THREAD

**Issue by Giordi10** [unrealities/MTGA_Draft_17Lands#72]
### Describe the bug in detail

The application get stuck after the P3 Pick 14 resulting impossibile to use the suggest deck function

### Steps to reproduce this bug

1. Start a Quick Draft
2. End the draft phase
3. Get stuck

### Operating System

Windows

### Operating System Version

Windows 11

### Run Type

Windows Executable

**Comment by unrealities** [comment]
I've released v3.30. Please let me know if this helps with the issue.

**Comment by Giordi10** [comment]
Nope, still the issue is still here.

https://imgur.com/a/GT8cPIV

**Comment by Giordi10** [comment]
It get stuck on that moment. If i go to "Cards" and "Suggest Decks" it doesn't suggest me a deck at all, the list is empty.

**Comment by unrealities** [comment]
Ok. I think that is because the suggest deck isn't the best with 3+ color decks. You don't have any multicolor lands, so it's struggling to put together a deck. It looks like BW would be your only option it might accept, and I'm guessing based the score is too low to show as it's not worth playing.

**Comment by Giordi10** [comment]
Ok got it, makes sense.
Thank you for your time :)
